
const OPEN_VIEW_MAIN = 'OPEN_VIEW_MAIN'
const OPEN_VIEW_LOCATION = 'OPEN_VIEW_LOCATION'
const OPEN_VIEW_VERIFY_DIGITS = 'OPEN_VIEW_VERIFY_DIGITS'
const MAIN_VIEW_IS_OPENED = 'MAIN_VIEW_OPENED'
const LOCATION_VIEW_IS_OPENED = 'LOCATION_VIEW_IS_OPENED'
const VERIFY_DIGITS_VIEW_IS_OPENED = 'VERIFY_DIGITS_VIEW_IS_OPENED'
const DIGIT_CHANGED = 'DIGIT_CHANGED'
const ADD_DIGIT_INPUT = 'ADD_DIGIT_INPUT'

export {
  OPEN_VIEW_MAIN,
  OPEN_VIEW_LOCATION,
  OPEN_VIEW_VERIFY_DIGITS,
  MAIN_VIEW_IS_OPENED,
  LOCATION_VIEW_IS_OPENED,
  VERIFY_DIGITS_VIEW_IS_OPENED,
  DIGIT_CHANGED,
  ADD_DIGIT_INPUT,
}
